{{- if not .Values.superadmin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: boilstream-superadmin
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "boilstream.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ required ".Values.superadmin.password is required when superadmin.existingSecret is empty" .Values.superadmin.password | quote }}
{{- end }}
