global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "boilstream"
    static_configs:
      - targets: ["host.docker.internal:8081"]
    metrics_path: /metrics
    scrape_interval: 1s
