apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://boilstream-prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "1s"
      queryTimeout: "60s"
      httpMethod: "POST"
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: prometheus